<Project>
	<PropertyGroup>
		<SolutionDir Condition="'$(SolutionDir)' == '' ">$(MSBuildThisFileDirectory)../../</SolutionDir>
	</PropertyGroup>

	<Target Name="GraphiteUiDocs_CopyLocalThemeContents" BeforeTargets="Build">
		<ItemGroup>
			<GraphiteUiDocsThemeFiles Include="$(SolutionDir)/GraphiteUi/Styles/**/*" />
		</ItemGroup>

		<Copy SourceFiles="@(GraphiteUiDocsThemeFiles)"
		      DestinationFolder="$(MSBuildProjectDirectory)/bin/GraphiteUi"
		      SkipUnchangedFiles="true" />
	</Target>
</Project>
