<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<!--<PropertyGroup>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	</PropertyGroup>-->

	<ItemGroup>
		<None Include="GraphiteUI.targets" Pack="true" PackagePath="buildTransitive\GraphiteUI.targets" />
		<None Include="Styles\*.cs" Pack="true" PackagePath="theme\components\%(Filename)%(Extension)" />
		<None Include="Styles\_theme.css" Pack="true" PackagePath="theme\theme.css" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageReference Include="LinkDotNet.StringBuilder" Version="2.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.8" />
    <PackageReference Include="TwMerge" Version="1.0.7" />
  </ItemGroup>

</Project>
