<!-- Copies style-related files to the output directory of a consuming project -->
<Project>
	<PropertyGroup>
		<GraphiteUiThemeDir Condition="'$(GraphiteUiThemeDir)' == '' and '$(GraphiteUI)' != ''">$(GraphiteUI)</GraphiteUiThemeDir>
		<GraphiteUiThemeDir Condition="'$(GraphiteUiThemeDir)' == ''">$(MSBuildProjectDirectory)\bin\GraphiteUi</GraphiteUiThemeDir>
	</PropertyGroup>

	<Target Name="GraphiteUi_CopyThemeContents" AfterTargets="Build">
		<ItemGroup>
			<GraphiteUiThemeFiles Include="$(MSBuildThisFileDirectory)..\theme\**\*" />
		</ItemGroup>

		<Copy SourceFiles="@(GraphiteUiThemeFiles)"
		      DestinationFolder="$(GraphiteUiThemeDir)"
		      SkipUnchangedFiles="true" />
	</Target>
</Project>
