<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>GraphiteUi</PackageId>
    <Version>0.5</Version>
    <Authors>Ivan Dmitriev</Authors>
    <Description>GraphiteUi is a Blazor UI component library for SSR and interactive rendering modes.</Description>
    <PackageTags>blazor;ui;components;razor</PackageTags>
    <PackageProjectUrl>https://github.com/IvanDmitriev1/GraphiteUi</PackageProjectUrl>
    <RepositoryUrl>https://github.com/IvanDmitriev1/GraphiteUi</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<!--<PropertyGroup>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	</PropertyGroup>-->

	<ItemGroup>
		<None Include="GraphiteUi.targets" Pack="true" PackagePath="buildTransitive\GraphiteUi.targets" />
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="Styles\*.cs" Pack="true" PackagePath="theme\components\%(Filename)%(Extension)" />
		<None Include="Styles\_theme.css" Pack="true" PackagePath="theme\theme.css" />
		<None Include="Styles\_dark.css" Pack="true" PackagePath="theme\_dark.css" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="LinkDotNet.StringBuilder" Version="3.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
    <PackageReference Include="TwMerge" Version="1.0.7" />
  </ItemGroup>

</Project>
