using GraphiteUi.Utilities;

namespace GraphiteUi.Styles;

public static class PopupStyles
{
    public static string RootClass { get; } = new CssClassBuilder(stackalloc char[256])
        .Add("relative")
        .Add("inline-flex")
        .Add("flex-col")
        .Add("data-[disabled=true]:opacity-disabled")
        .Add("data-[disabled=true]:pointer-events-none")
        .ToString();

    public static string TriggerClass { get; } = new CssClassBuilder(stackalloc char[512])
        .Add("inline-flex")
        .Add("items-center")
        .Add("justify-center")
        .Add("gap-2")
        .Add(CommonStyles.SurfaceFrameRegularClass)
        .Add("px-3")
        .Add("py-2")
        .Add("outline-hidden")
        .Add("transition-[background-color,border-color,box-shadow]")
        .Add(Utils.MotionReduceTransitionNone)
        .Add(ColorVariants.Surface.HoverBackground)
        .Add("focus-visible:ring")
        .Add("focus-visible:ring-primary-5")
        .Add("focus-visible:border-primary-20")
        .Add("data-[open=true]:bg-focus")
        .Add("data-[open=true]:border-primary-15")
        .Add("data-[open=true]:ring")
        .Add("data-[open=true]:ring-primary-5")
        .Add(ColorVariants.Disabled.Background)
        .Add(ColorVariants.Disabled.Foreground)
        .Add(Utils.DisabledCursorDefault)
        .ToString();

    public static string BackdropClass { get; } = new CssClassBuilder(stackalloc char[256])
        .Add("fixed")
        .Add("inset-0")
        .Add("z-40")
        .Add("bg-black/20")
        .Add("opacity-0")
        .Add("transition-opacity")
        .Add("duration-150")
        .Add("ease-out")
        .Add(Utils.MotionReduceTransitionNone)
        .Add("data-[state=open]:opacity-100")
        .Add("data-[state=closed]:opacity-0")
        .ToString();

    public static string ContentClass { get; } = new CssClassBuilder(stackalloc char[768])
        .Add("absolute")
        .Add("left-0")
        .Add("top-[calc(100%+0.5rem)]")
        .Add("z-50")
        .Add("min-w-40")
        .Add("rounded-lg")
        .Add("border")
        .Add(ColorVariants.Border.Default)
        .Add(ColorVariants.Surface.PopupBackground)
        .Add("p-2")
        .Add("shadow-sm")
        .Add("origin-top")
        .Add("opacity-0")
        .Add("translate-y-1")
        .Add("scale-[0.98]")
        .Add("transition-[opacity,transform]")
        .Add("duration-150")
        .Add("ease-out")
        .Add(Utils.MotionReduceTransitionNone)
        .Add("data-[state=open]:opacity-100")
        .Add("data-[state=open]:translate-y-0")
        .Add("data-[state=open]:scale-100")
        .Add("data-[state=closed]:opacity-0")
        .Add("data-[state=closed]:translate-y-1")
        .Add("data-[state=closed]:scale-[0.98]")
        .Add("data-[state=closed]:pointer-events-none")
        .ToString();
}
