using GraphiteUi.Utilities;

namespace GraphiteUi.Styles;

public static class PopupStyles
{
    public static string RootClass { get; } = new CssClassBuilder(stackalloc char[256])
        .Add("relative")
        .Add("inline-flex")
        .Add("flex-col")
        .Add(Utils.DataDisabled)
        .ToString();

    public static string TriggerClass { get; } = new CssClassBuilder(stackalloc char[640])
        .Add("inline-flex")
        .Add("relative")
        .Add("z-50")
        .Add("items-center")
        .Add("justify-center")
        .Add("gap-2")
        .Add("h-10")
        .Add(CommonStyles.ControlFrameClass)
        .Add("text-body-sm")
        .Add("font-medium")
        .Add("px-4")
        .Add("cursor-pointer")
        .Add("transition-[background-color,border-color,box-shadow]")
        .Add(Utils.MotionReduceTransitionNone)
        .Add(ColorVariants.Surface.HoverBackground)
        .Add(Utils.FocusVisible)
        .Add("data-[open=true]:bg-neutral-10")
        .Add("data-[open=true]:border-neutral-20")
        .Add(ColorVariants.Disabled.Background)
        .Add(ColorVariants.Disabled.Foreground)
        .Add(Utils.DisabledCursorDefault)
        .ToString();

    public static string BackdropClass { get; } = new CssClassBuilder(stackalloc char[320])
        .Add("fixed")
        .Add("inset-0")
        .Add("z-40")
        // Single scrim token. Popup, drawer and dialog previously used black/20,
        // black/30 and background/40 respectively.
        .Add("bg-scrim")
        .Add("opacity-0")
        .Add("transition-opacity")
        .Add("data-[state=open]:duration-220")
        .Add("data-[state=open]:ease-[cubic-bezier(0.16,1,0.3,1)]")
        .Add("data-[state=closed]:duration-220")
        .Add("data-[state=closed]:ease-[cubic-bezier(0.16,1,0.3,1)]")
        .Add(Utils.MotionReduceTransitionNone)
        .Add("data-[state=open]:opacity-100")
        .Add("data-[state=closed]:opacity-0")
        .Add("data-[state=closed]:pointer-events-none")
        .ToString();

    public static string ContentClass { get; } = new CssClassBuilder(stackalloc char[768])
        .Add("absolute")
        .Add("left-0")
        .Add("top-[calc(100%+0.5rem)]")
        .Add("z-50")
        .Add("w-full")
        .Add("min-w-40")
        .Add("rounded-lg")
        .Add("border")
        .Add(ColorVariants.Border.Default)
        .Add(ColorVariants.Surface.PopupBackground)
        .Add("p-2")
        .Add("shadow-lg")
        .Add("origin-top")
        .Add("transform-gpu")
        .Add("will-change-transform")
        .Add("opacity-0")
        .Add("translate-y-1")
        .Add("scale-[0.98]")
        .Add("transition-[opacity,transform]")
        .Add("data-[state=open]:duration-240")
        .Add("data-[state=open]:ease-[cubic-bezier(0.16,1,0.3,1)]")
        .Add("data-[state=closed]:duration-240")
        .Add("data-[state=closed]:ease-[cubic-bezier(0.16,1,0.3,1)]")
        .Add(Utils.MotionReduceTransitionNone)
        .Add("data-[state=open]:opacity-100")
        .Add("data-[state=open]:translate-y-0")
        .Add("data-[state=open]:scale-100")
        .Add("data-[state=closed]:opacity-0")
        .Add("data-[state=closed]:translate-y-1")
        .Add("data-[state=closed]:scale-[0.98]")
        .Add("data-[state=closed]:pointer-events-none")
        .ToString();
}
