using GraphiteUi.Utilities;

namespace GraphiteUi.Styles;

public static class SkeletonStyles
{
    public static string RootClass { get; } = new CssClassBuilder(stackalloc char[512])
        .Add("relative")
        .Add("transition-opacity")
        .Add("duration-150")
        .Add("ease-out")
        .Add(Utils.MotionReduceTransitionNone)
        .Add("data-[loading=true]:pointer-events-none")
        .Add("data-[loading=true]:select-none")
        .Add("data-[loading=true]:cursor-wait")
        .Add("data-[loading=true]:overflow-hidden")
        .ToString();

    public static string ContentClass { get; } = new CssClassBuilder(stackalloc char[256])
        .Add("relative")
        .Add("transition-[opacity,color,background-color,border-color]")
        .Add("duration-150")
        .Add("ease-out")
        .Add(Utils.MotionReduceTransitionNone)
        .ToString();

    public static string AutoMimicClass { get; } = new CssClassBuilder(stackalloc char[2048])
        .Add(ContentClass)
        .Add("[&_[data-slot=input-wrapper]]:bg-neutral-10")
        .Add("[&_[data-slot=input-wrapper]]:bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("[&_[data-slot=input-wrapper]]:bg-[length:200%_100%]")
        .Add("[&_[data-slot=input-wrapper]]:animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("[&_[data-slot=input-wrapper]]:motion-reduce:animate-none")
        .Add("[&_[data-slot=input-wrapper]]:border-transparent")
        .Add("[&_[data-slot=input-wrapper]]:shadow-none")
        .Add("[&_[data-slot=popup-trigger]]:bg-neutral-10")
        .Add("[&_[data-slot=popup-trigger]]:bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("[&_[data-slot=popup-trigger]]:bg-[length:200%_100%]")
        .Add("[&_[data-slot=popup-trigger]]:animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("[&_[data-slot=popup-trigger]]:motion-reduce:animate-none")
        .Add("[&_[data-slot=popup-trigger]]:border-transparent")
        .Add("[&_[data-slot=popup-trigger]]:shadow-none")
        .Add("[&_button]:border-transparent")
        .Add("[&_button]:shadow-none")
        .Add("[&_[data-slot=label]]:!left-0")
        .Add("[&_[data-slot=label]]:!top-0")
        .Add("[&_[data-slot=label]]:!translate-y-[-24px]")
        .Add("[&_[data-slot=label]]:!h-4")
        .Add("[&_[data-slot=label]]:!w-28")
        .Add("[&_[data-slot=label]]:!rounded-md")
        .Add("[&_[data-slot=label]]:!bg-neutral-10")
        .Add("[&_[data-slot=label]]:!bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("[&_[data-slot=label]]:!bg-[length:200%_100%]")
        .Add("[&_[data-slot=label]]:!animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("[&_[data-slot=label]]:motion-reduce:!animate-none")
        .Add("[&_[data-slot=label]]:!text-transparent")
        .Add("[&_[data-slot=label]]:!overflow-hidden")
        .Add("[&_[data-slot=label]]:!pe-0")
        .Add("[&_[data-slot=label]]:!max-w-none")
        .Add("[&_input]:text-transparent")
        .Add("[&_textarea]:text-transparent")
        .Add("[&_select]:text-transparent")
        .Add("[&_button]:text-transparent")
        .Add("[&_label]:text-transparent")
        .Add("[&_span]:text-transparent")
        .Add("[&_p]:text-transparent")
        .Add("[&_a]:text-transparent")
        .Add("[&_option]:text-transparent")
        .Add("[&_input]:placeholder:text-transparent")
        .Add("[&_textarea]:placeholder:text-transparent")
        .Add("[&_input]:caret-transparent")
        .Add("[&_textarea]:caret-transparent")
        .Add("[&_button]:bg-neutral-10")
        .Add("[&_button]:bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("[&_button]:bg-[length:200%_100%]")
        .Add("[&_button]:animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("[&_button]:motion-reduce:animate-none")
        .Add("[&_[data-slot=input]]:bg-transparent")
        .Add("[&_[data-slot=select-input]]:bg-transparent")
        .Add("[&_[data-slot=input]]:opacity-0")
        .Add("[&_[data-slot=select-input]]:opacity-0")
        .Add("[&_textarea]:bg-transparent")
        .Add("[&_select]:bg-transparent")
        .Add("[&_[data-slot=popup-content]]:hidden")
        .Add("[&_[data-slot=popup-backdrop]]:hidden")
        .Add("[&_svg]:opacity-0")
        .Add("[&_img]:opacity-0")
        .ToString();

    public static string BlockClass { get; } = new CssClassBuilder(stackalloc char[1024])
        .Add("relative")
        .Add("w-full")
        .Add("min-h-4")
        .Add("overflow-hidden")
        .Add("rounded-md")
        .Add("bg-neutral-10")
        .Add("text-transparent")
        .Add("pointer-events-none")
        .Add("bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("bg-[length:200%_100%]")
        .Add("animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("motion-reduce:animate-none")
        .ToString();

    public static string LineClass { get; } = new CssClassBuilder(stackalloc char[1024])
        .Add("relative")
        .Add("h-4")
        .Add("w-full")
        .Add("overflow-hidden")
        .Add("rounded-md")
        .Add("bg-neutral-10")
        .Add("text-transparent")
        .Add("pointer-events-none")
        .Add("bg-[linear-gradient(110deg,var(--color-shimmer-from)_0%,var(--color-shimmer-via)_50%,var(--color-shimmer-from)_100%)]")
        .Add("bg-[length:200%_100%]")
        .Add("animate-[graphite-skeleton-shimmer_1.2s_linear_infinite]")
        .Add("motion-reduce:animate-none")
        .ToString();
}
